import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteHeader from "@/components/headerbar.jsx";
import SiteFooter from "@/components/footer.jsx";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-screen flex flex-col bg-gradient-to-br from-green-50 via-white to-green-50">
          <SiteHeader />
          {/* Main Content with Padding */}
          <main className="flex-grow">
            {children}
          </main>
          
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
